eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.143:7001/eureka/
server:
  port: 7005
spring:
  redis:
    host: 192.168.1.143
    port: 6379
    pool:
      max-active: 8
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
  zipkin:
    enabled: false
    base-url: http://192.168.1.149:9002
logging:
  file: /opt/jxty/logs/gen.log
  level:
    root: info
    ufast: info
