eureka:
  client:
    service-url:
      defaultZone: http://10.100.2.109:18001/eureka/
server:
  port: 18002
spring:
  redis:
    host: 10.100.2.106
    port: 6379
    pool:
      max-active: 8
  cloud:
    inetutils:
      preferred-networks:
        - 10.100
#  zipkin:
#    enabled: false
#    base-url: http://192.168.1.149:9002

