eureka:
  client:
    service-url:
      defaultZone: =http://eureka.jt.com:9000/eureka/
server:
  port: 7005
spring:
  redis:
    host: redis.jt.com
    port: 6379
    pool:
      max-active: 8
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
  zipkin:
    enabled: false
    base-url: http://192.168.1.149:9002
logging:
  file: genlog
  level:
    root: info
    ufast: info